version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nama-database
      POSTGRES_USER: nama-username
      POSTGRES_PASSWORD: nama-password
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
